### ISSUE TITLE
negative AAAB resum at low K

### ISSUE THREAD

**Issue by shifanmao** [qmacAstanford/MultiPointCalculation#5]
with the following inputs, IAAABresum in multipoint.py is giving negative numbers.

FA = 0.5
N = 1e4
lams = [0,0,0,0]
props = [p1, p2, p3] with magnitudes of wave vectors
norm(p1.kvec) = K
norm(p2.kvec) = 2K (or 1.5K)
norm(p3.kvec) = K

mp.IAAABresum(N, FA, *lams, *props) at K = 1e-2

**Comment by qmacAstanford** [comment]
I think I have fixed this problem.  Now IAAABrsum appears to be accurate for any large N and intermediate K.  There is a decent plateau for arbitrarily high N.  The change was a more accurate way to calculate special.f3.

Let me know if this doesn't fix the problem!

PS: When N<~0.01 there is an inaccuracy due to limited number of eigenvalues.  You had asked about this so I thought I'd mention it.

**Comment by shifanmao** [comment]
Thank you Quinn. I tested with the above inputs (N=1e4, FA=0.5) and S4 is now finite at K=1e-2.

Everything below N=1e3 is still consistent with previous calculations.

I'm closing this issue.
